"""Loads this system's own ONNX detector family (as generated by
`backend.scenarios.asset_generator.AssetGenerator.generate_detector_onnx`)
into an equivalent, differentiable PyTorch module with the *actual* ONNX
weights transplanted in -- not an independently-initialized architectural
lookalike. This is what makes gradient-based trigger reconstruction
(`trigger_reconstruction.py`) a genuine analysis of the real model under
test, not of some other network that merely has the same layer shapes.

Scope, stated plainly: this bridge only understands this system's own
five-initializer detector graph (three backbone convs + a 1x1 head + an
additive 8x8 trigger branch). It does not attempt to be a general
ONNX-to-PyTorch converter -- that's a much larger undertaking (arbitrary
op coverage, control flow, etc.) than gradient-based reconstruction needs
to justify. A model whose graph doesn't match this exact signature is
correctly reported as unsupported by `can_bridge_to_torch`, not silently
mis-mapped onto the wrong architecture.
"""
import onnx
from onnx import numpy_helper


REQUIRED_INITIALIZERS = {"b1_w", "b2_w", "b3_w", "head_w", "trigger_w"}


def can_bridge_to_torch(onnx_path: str) -> bool:
    """Structural compatibility check: does this ONNX file's graph match
    the exact initializer signature this bridge knows how to transplant?
    Used to decide, before attempting reconstruction, whether to report
    the model as bridgeable or explicitly UNAVAILABLE."""
    try:
        model = onnx.load(onnx_path)
    except Exception:
        return False
    names = {init.name for init in model.graph.initializer}
    return REQUIRED_INITIALIZERS.issubset(names)


def load_intelx_detector_as_torch(onnx_path: str):
    """Returns (torch_module, input_size, num_channels) with real weights
    loaded from the ONNX file and gradients disabled on every parameter
    (Neural Cleanse optimizes the INPUT trigger, never the model itself)."""
    import torch
    import torch.nn as nn

    if not can_bridge_to_torch(onnx_path):
        raise ValueError(
            f"'{onnx_path}' does not match this system's own detector graph signature "
            f"(needs initializers {sorted(REQUIRED_INITIALIZERS)}); cannot bridge to a "
            "differentiable PyTorch module for gradient-based trigger reconstruction."
        )

    model = onnx.load(onnx_path)
    tensors = {init.name: numpy_helper.to_array(init) for init in model.graph.initializer}

    b1_w, b2_w, b3_w = tensors["b1_w"], tensors["b2_w"], tensors["b3_w"]
    head_w, trigger_w = tensors["head_w"], tensors["trigger_w"]
    num_channels = head_w.shape[0]

    input_tensor = model.graph.input[0]
    input_size = input_tensor.type.tensor_type.shape.dim[2].dim_value or 640

    class BridgedDetector(nn.Module):
        def __init__(self):
            super().__init__()
            self.b1 = nn.Conv2d(3, b1_w.shape[0], 3, stride=2, padding=1, bias=False)
            self.b2 = nn.Conv2d(b1_w.shape[0], b2_w.shape[0], 3, stride=2, padding=1, bias=False)
            self.b3 = nn.Conv2d(b2_w.shape[0], b3_w.shape[0], 3, stride=2, padding=1, bias=False)
            self.head = nn.Conv2d(b3_w.shape[0], num_channels, 1, bias=False)
            self.trigger = nn.Conv2d(3, num_channels, 8, stride=8, bias=False)
            self.relu = nn.ReLU()

            with torch.no_grad():
                self.b1.weight.copy_(torch.from_numpy(b1_w.copy()))
                self.b2.weight.copy_(torch.from_numpy(b2_w.copy()))
                self.b3.weight.copy_(torch.from_numpy(b3_w.copy()))
                self.head.weight.copy_(torch.from_numpy(head_w.copy()))
                self.trigger.weight.copy_(torch.from_numpy(trigger_w.copy()))
            for p in self.parameters():
                p.requires_grad_(False)

        def forward(self, x):
            b = self.relu(self.b1(x))
            b = self.relu(self.b2(b))
            b = self.relu(self.b3(b))
            head_out = self.head(b)
            trigger_out = self.trigger(x)
            combined = head_out + trigger_out
            # (batch, channels, H, W) -> (batch, channels, H*W), matching the
            # ONNX graph's own trailing Reshape node.
            n, c, h, w = combined.shape
            return combined.reshape(n, c, h * w)

    torch_model = BridgedDetector()
    torch_model.eval()
    return torch_model, int(input_size), int(num_channels)
